# Occitan (post 1500) translation for apport
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-09-10 11:16+0200\n"
"PO-Revision-Date: 2015-04-27 21:47+0000\n"
"Last-Translator: Cédric VALMARY (Tot en òc) <cvalmary@yahoo.fr>\n"
"Language-Team: Occitan (post 1500) <oc@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2015-12-05 05:10+0000\n"
"X-Generator: Launchpad (build 17862)\n"
"Language: \n"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:1
#: ../debian/tmp/usr/share/apport/apport-kde.py:468
#: ../debian/tmp/usr/share/apport/apport-kde.py:503
#: ../debian/tmp/usr/share/apport/apport-kde.py:522 ../gtk/apport-gtk.ui.h:1
#: ../kde/apport-kde.py:468 ../kde/apport-kde.py:503 ../kde/apport-kde.py:522
msgid "Apport"
msgstr "Apòrt"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:2 ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "Abandonar"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:3 ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "D'acòrdi"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:4 ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "Rapòrt d'anomalia"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:5 ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>O planhèm, una error intèrna s'es producha !</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:6
#: ../debian/tmp/usr/share/apport/apport-kde.py:240 ../gtk/apport-gtk.ui.h:6
#: ../gtk/apport-gtk.py:300 ../debian/tmp/usr/share/apport/apport-gtk.py:300
#: ../kde/apport-kde.py:240
msgid "If you notice further problems, try restarting the computer."
msgstr "En cas de problèmas mai, ensajatz de reamodar vòstre ordenador."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:7 ../gtk/apport-gtk.ui.h:7
msgid "Send an error report to help fix this problem"
msgstr "Mandar un rapòrt d'anomalia per ajudar a resòlvre aqueste problèma"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:8 ../gtk/apport-gtk.ui.h:8
msgid "Ignore future problems of this program version"
msgstr "Ignorar los problèmas que venon d'aquesta version del programa"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:9
#: ../debian/tmp/usr/share/apport/apport-kde.py:291 ../gtk/apport-gtk.ui.h:9
#: ../gtk/apport-gtk.py:204 ../gtk/apport-gtk.py:573
#: ../debian/tmp/usr/share/apport/apport-gtk.py:204
#: ../debian/tmp/usr/share/apport/apport-gtk.py:573 ../kde/apport-kde.py:291
msgid "Show Details"
msgstr "Afichar los detalhs"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:10 ../gtk/apport-gtk.ui.h:10
msgid "_Examine locally"
msgstr "_Examinar en local"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:11
#: ../debian/tmp/usr/share/apport/apport-kde.py:233 ../gtk/apport-gtk.ui.h:11
#: ../gtk/apport-gtk.py:287 ../debian/tmp/usr/share/apport/apport-gtk.py:287
#: ../kde/apport-kde.py:233
msgid "Leave Closed"
msgstr "Daissar tampat"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:12
#: ../debian/tmp/usr/share/apport/apport-kde.py:230
#: ../debian/tmp/usr/share/apport/apport-kde.py:243 ../gtk/apport-gtk.ui.h:12
#: ../gtk/apport-gtk.py:216 ../gtk/apport-gtk.py:284 ../gtk/apport-gtk.py:303
#: ../debian/tmp/usr/share/apport/apport-gtk.py:216
#: ../debian/tmp/usr/share/apport/apport-gtk.py:284
#: ../debian/tmp/usr/share/apport/apport-gtk.py:303 ../kde/apport-kde.py:230
#: ../kde/apport-kde.py:243
msgid "Continue"
msgstr "Contunhar"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:13 ../gtk/apport-gtk.ui.h:13
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>A collectar d'informacions ligadas al problèma</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:14 ../gtk/apport-gtk.ui.h:14
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr ""
"De donadas son en cors de collècta per ajudar los desvolopaires a corregir "
"lo problèma qu'avètz rencontrat."

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:15
#: ../debian/tmp/usr/share/apport/apport-kde.py:434 ../gtk/apport-gtk.ui.h:15
#: ../debian/tmp/usr/bin/apport-cli.py:251 ../bin/apport-cli.py:251
#: ../kde/apport-kde.py:434
msgid "Uploading problem information"
msgstr "Mandadís de las informacions ligadas al problèma"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:16 ../gtk/apport-gtk.ui.h:16
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>Mandadís de las informacions ligadas a l'incident</b></big>"

#: ../debian/tmp/usr/share/apport/apport-gtk.ui.h:17
#: ../debian/tmp/usr/share/apport/apport-kde.py:435 ../gtk/apport-gtk.ui.h:17
#: ../kde/apport-kde.py:435
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr ""
"Las donadas collectadas son transmesas al sistèma de seguit dels bugs. Aquò "
"pòt prene qualques minutas."

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "Fichièr d'arrèst brutal d'Apport"

#: ../debian/tmp/usr/share/apport/apport-kde.py:362 ../gtk/apport-gtk.py:142
#: ../debian/tmp/usr/share/apport/apport-gtk.py:142
#: ../debian/tmp/usr/bin/apport-cli.py:150 ../bin/apport-cli.py:150
#: ../kde/apport-kde.py:362
msgid "(binary data)"
msgstr "(donadas binàrias)"

#: ../gtk/apport-gtk.py:157 ../debian/tmp/usr/share/apport/apport-gtk.py:157
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "O planhèm, %s s'es arrestada d'un biais inesperat."

#: ../gtk/apport-gtk.py:160 ../debian/tmp/usr/share/apport/apport-gtk.py:160
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "O planhèm, %s a quitat d'un biais imprevist."

#: ../debian/tmp/usr/share/apport/apport-kde.py:199
#: ../debian/tmp/usr/share/apport/apport-kde.py:237 ../gtk/apport-gtk.py:165
#: ../debian/tmp/usr/share/apport/apport-gtk.py:165 ../kde/apport-kde.py:199
#: ../kde/apport-kde.py:237
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "O planhèm, %s a rencontrat una error intèrna."

#: ../debian/tmp/usr/share/apport/apport-kde.py:185 ../gtk/apport-gtk.py:177
#: ../debian/tmp/usr/share/apport/apport-gtk.py:177
#: ../debian/tmp/usr/bin/apport-cli.py:178 ../bin/apport-cli.py:178
#: ../kde/apport-kde.py:185
msgid "Send problem report to the developers?"
msgstr "Mandar un rapòrt d'errors als desvolopaires ?"

#: ../debian/tmp/usr/share/apport/apport-kde.py:193 ../gtk/apport-gtk.py:186
#: ../debian/tmp/usr/share/apport/apport-gtk.py:186 ../kde/apport-kde.py:193
msgid "Send"
msgstr "Mandar"

#: ../gtk/apport-gtk.py:228 ../debian/tmp/usr/share/apport/apport-gtk.py:228
msgid "Force Closed"
msgstr "Tampat de fòrça"

#: ../debian/tmp/usr/share/apport/apport-kde.py:234
#: ../debian/tmp/usr/share/apport/apport-kde.py:380 ../gtk/apport-gtk.py:229
#: ../gtk/apport-gtk.py:288 ../debian/tmp/usr/share/apport/apport-gtk.py:229
#: ../debian/tmp/usr/share/apport/apport-gtk.py:288 ../kde/apport-kde.py:234
#: ../kde/apport-kde.py:380
msgid "Relaunch"
msgstr "Reaviar"

#: ../gtk/apport-gtk.py:238 ../debian/tmp/usr/share/apport/apport-gtk.py:238
#, python-format
msgid "The application %s has stopped responding."
msgstr "L'aplicacion %s a daissat de respondre."

#: ../gtk/apport-gtk.py:242 ../debian/tmp/usr/share/apport/apport-gtk.py:242
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "Lo programa \"%s\" a daissat de respondre."

#: ../debian/tmp/usr/share/apport/apport-kde.py:207 ../gtk/apport-gtk.py:257
#: ../debian/tmp/usr/share/apport/apport-gtk.py:257 ../kde/apport-kde.py:207
#, python-format
msgid "Package: %s"
msgstr "Paquet : %s"

#: ../debian/tmp/usr/share/apport/apport-kde.py:213 ../gtk/apport-gtk.py:264
#: ../debian/tmp/usr/share/apport/apport-gtk.py:264 ../kde/apport-kde.py:213
msgid "Sorry, a problem occurred while installing software."
msgstr ""
"O planhèm, una error s'es producha al moment de l'installacion del logicial."

#: ../debian/tmp/usr/share/apport/apport-kde.py:219 ../gtk/apport-gtk.py:273
#: ../gtk/apport-gtk.py:292 ../debian/tmp/usr/share/apport/apport-gtk.py:273
#: ../debian/tmp/usr/share/apport/apport-gtk.py:292 ../kde/apport-kde.py:219
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "L'aplicacion %s a patit una error intèrna."

#: ../debian/tmp/usr/share/apport/apport-kde.py:222 ../gtk/apport-gtk.py:276
#: ../debian/tmp/usr/share/apport/apport-gtk.py:276 ../kde/apport-kde.py:222
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "L'aplicacion %s a quitat d'un biais imprevist."

#: ../debian/tmp/usr/share/apport/apport-kde.py:244 ../gtk/apport-gtk.py:304
#: ../debian/tmp/usr/share/apport/apport-gtk.py:304 ../kde/apport-kde.py:244
msgid "Ignore future problems of this type"
msgstr "Ignorar los problèmas d'aquesta mena que venon"

#: ../debian/tmp/usr/share/apport/apport-kde.py:288 ../gtk/apport-gtk.py:577
#: ../debian/tmp/usr/share/apport/apport-gtk.py:577 ../kde/apport-kde.py:288
msgid "Hide Details"
msgstr "Amagar los detalhs"

#: ../bin/apport-unpack.py:22 ../debian/tmp/usr/bin/apport-unpack.py:22
#, python-format
msgid "Usage: %s <report> <target directory>"
msgstr "Utilizacion : %s <rapòrt> <dorsièr cibla>"

#: ../bin/apport-unpack.py:46 ../debian/tmp/usr/bin/apport-unpack.py:46
msgid "Destination directory exists and is not empty."
msgstr "Lo dorsièr de destinacion existís ja e es pas void."

#: ../debian/tmp/usr/share/apport/apport-kde.py:314 ../kde/apport-kde.py:314
msgid "Username:"
msgstr "Nom d'utilizaire :"

#: ../debian/tmp/usr/share/apport/apport-kde.py:315 ../kde/apport-kde.py:315
msgid "Password:"
msgstr "Senhal :"

#: ../debian/tmp/usr/share/apport/apport-kde.py:405 ../kde/apport-kde.py:405
msgid "Collecting Problem Information"
msgstr "Collècta de las informacions ligadas al problèma"

#: ../debian/tmp/usr/share/apport/apport-kde.py:406
#: ../debian/tmp/usr/bin/apport-cli.py:238 ../bin/apport-cli.py:238
#: ../kde/apport-kde.py:406
msgid "Collecting problem information"
msgstr "Collècta d'informacions ligadas al problèma"

#: ../debian/tmp/usr/share/apport/apport-kde.py:407 ../kde/apport-kde.py:407
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"Las informations collectadas pòdon èsser mandadas als desvolopaires per "
"melhorar l'aplicacion. Aquò pòt prene qualques minutas."

#: ../debian/tmp/usr/share/apport/apport-kde.py:433 ../kde/apport-kde.py:433
msgid "Uploading Problem Information"
msgstr "Mandadís de las informacions ligadas al problèma"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "Collectar d'informacions a prepaus del sistèma"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr ""
"Una autentificacion es necessària per collectar l'informacion del sistèma "
"requesida per aqueste rapòrt de bug"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "Rapòrts de problèmas sistèma"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid ""
"Please enter your password to access problem reports of system programs"
msgstr ""
"Picatz vòstre senhal per accedir a de rapòrts de problèmas de programas "
"sistèma"

#: ../kde/apport-kde-mime.desktop.in.h:1 ../kde/apport-kde.desktop.in.h:1
#: ../gtk/apport-gtk.desktop.in.h:1
msgid "Report a problem..."
msgstr "Senhalar un problèma..."

#: ../kde/apport-kde-mime.desktop.in.h:2 ../kde/apport-kde.desktop.in.h:2
#: ../gtk/apport-gtk.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr "Senhalar un disfoncionament als desvolopaires"

#: ../debian/tmp/usr/bin/apport-valgrind.py:37 ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "Vejatz la pagina de manual per mai de detalhs."

#: ../debian/tmp/usr/bin/apport-valgrind.py:43 ../bin/apport-valgrind.py:43
msgid "specify the log file name produced by valgrind"
msgstr "especifica lo nom del fichièr jornal produch per valgrind"

#: ../debian/tmp/usr/bin/apport-valgrind.py:46 ../bin/apport-valgrind.py:46
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr ""
"reütilizar un repertòri de nauc de sabla (« sandbox ») (SDIR) creat "
"precedentament o, s'existís pas, lo crear"

#: ../debian/tmp/usr/bin/apport-valgrind.py:50 ../bin/apport-valgrind.py:50
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"crear pas o reütilizar pas un repertòri sandbox per de simbòls de desbugatge "
"addicionals mas s'apuejar solament suls simbòls de desbugatge instaltats."

#: ../debian/tmp/usr/bin/apport-valgrind.py:54 ../bin/apport-valgrind.py:54
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr ""
"reütilizar un repertòri d'escondedor (CDIR) precedentament creat o, "
"s'existís pas, lo crear"

#: ../debian/tmp/usr/bin/apport-valgrind.py:58 ../bin/apport-valgrind.py:58
msgid ""
"report download/install progress when installing packages into sandbox"
msgstr ""
"afichar la progression del telecargament e de l'installacion al moment de "
"l'installacion de paquets dins lo nauc de sabla (« sandbox »)"

#: ../debian/tmp/usr/bin/apport-valgrind.py:62 ../bin/apport-valgrind.py:62
msgid ""
"the executable that is run under valgrind's memcheck tool  for memory leak "
"detection"
msgstr ""
"l'executable aviat dins l'aisina de verificacion de la memòria de valgrind "
"per detectar un pèrda de memòria."

#: ../debian/tmp/usr/bin/apport-valgrind.py:66 ../bin/apport-retrace.py:63
#: ../bin/apport-valgrind.py:66 ../debian/tmp/usr/bin/apport-retrace.py:63
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr ""
"Installar un paquet suplementari dins lo nauc de sabla (pòt èsser "
"especificat mantun còp)"

#: ../debian/tmp/usr/bin/apport-valgrind.py:97 ../bin/apport-valgrind.py:97
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "Error : %s es pas un executable. Arrèst."

#: ../data/kernel_oops.py:29 ../debian/tmp/usr/share/apport/kernel_oops.py:29
msgid "Your system might become unstable now and might need to be restarted."
msgstr ""
"Ara, vòstre sistèma se pòt  far instable e pòt aver besonh d'èsser reaviat."

#: ../bin/apport-retrace.py:34 ../debian/tmp/usr/bin/apport-retrace.py:34
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr ""
"Plaçar pas las « traças » novèlas dins lo rapòrt de bug, mas los escriure "
"sus la sortida estandarda."

#: ../bin/apport-retrace.py:36 ../debian/tmp/usr/bin/apport-retrace.py:36
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"Avia una sesilha gdb interactiva amb l'imatge memòria (core dump) del rapòrt "
"(-0 ignorat ; reescriu pas lo rapòrt)"

#: ../bin/apport-retrace.py:38 ../debian/tmp/usr/bin/apport-retrace.py:38
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr ""
"Escriu lo rapòrt dins un fichièr donat puslèu que de modificar lo rapòrt "
"d'origina."

#: ../bin/apport-retrace.py:41 ../debian/tmp/usr/bin/apport-retrace.py:41
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr ""
"Suprimir l'imatge memòria (core dump) del compte rendut aprèp regeneracion "
"de l'estat de la pila"

#: ../bin/apport-retrace.py:43 ../debian/tmp/usr/bin/apport-retrace.py:43
msgid "Override report's CoreFile"
msgstr "Espotir lo fichièr d'imatge memòria (CoreFile) del rapòrt"

#: ../bin/apport-retrace.py:45 ../debian/tmp/usr/bin/apport-retrace.py:45
msgid "Override report's ExecutablePath"
msgstr "Espotir l'emplaçament de l'executable (ExecutablePath) del rapòrt"

#: ../bin/apport-retrace.py:47 ../debian/tmp/usr/bin/apport-retrace.py:47
msgid "Override report's ProcMaps"
msgstr "Espotir la lista dels processus (ProcMaps) del rapòrt"

#: ../bin/apport-retrace.py:49 ../debian/tmp/usr/bin/apport-retrace.py:49
msgid "Rebuild report's Package information"
msgstr "Tornar construire las informacions suls paquets del rapòrt"

#: ../bin/apport-retrace.py:51 ../debian/tmp/usr/bin/apport-retrace.py:51
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"Metre en plaça un nauc de sabla temporari e i telecargar/installar los "
"paquets e los simbòls de desbugatge necessaris ; sens aquesta opcion, serà "
"supausat que los paquets e los simbòls de desbugatge necessaris son ja "
"installats sul sistèma. L'argument punta cap al dorsièr de configuracion de "
"basa del sistèma de creacion de paquets ; s'especificatz \"system\",  los "
"fichièrs de configuracion del sistèma seràn utilizats, mas sols los "
"plantatges de la version en cors d'execucion poiràn èsser traçats."

#: ../bin/apport-retrace.py:53 ../debian/tmp/usr/bin/apport-retrace.py:53
msgid ""
"Report download/install progress when installing packages into sandbox"
msgstr ""
"Senhalar l'avançament del telecargament/de l'installacion pendent "
"l'installacion de paquets dins lo nauc de sabla."

#: ../bin/apport-retrace.py:55 ../debian/tmp/usr/bin/apport-retrace.py:55
msgid "Prepend timestamps to log messages, for batch operation"
msgstr ""
"Prefixar un orodatatge als messatges de jornal, per un tractament per lòts"

#: ../bin/apport-retrace.py:57 ../debian/tmp/usr/bin/apport-retrace.py:57
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr ""
"Crear e utilizar de depauses tèrces a partir d'originas especificadas dins "
"de rapòrts"

#: ../bin/apport-retrace.py:59 ../debian/tmp/usr/bin/apport-retrace.py:59
msgid "Cache directory for packages downloaded in the sandbox"
msgstr ""
"Repertòri d'escondedor pels paquets telecargats dins lo nauc de sabla"

#: ../bin/apport-retrace.py:61 ../debian/tmp/usr/bin/apport-retrace.py:61
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"Repertòri pels paquets descompressats. Las execucions futuras presumiràn "
"qu'un paquet ja telecargat serà tanben extrach dins aqueste nauc de sabla."

#: ../bin/apport-retrace.py:65 ../debian/tmp/usr/bin/apport-retrace.py:65
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"Emplaçant d'un fichièr que conten las informacions d'autentificacion a la "
"banca de donadas dels plantatges. Aquò's utilizat quand òm indica un ID de "
"plantatge per cargar l'estat de la pila (solzment se -g, -o o -s son pas "
"especificats)"

#: ../bin/apport-retrace.py:67 ../debian/tmp/usr/bin/apport-retrace.py:67
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr ""
"Afichar l'estat de la pila reconstituida e demandar una confirmacion abans "
"de lo mandar a la banca de donadas dels plantatges."

#: ../bin/apport-retrace.py:69 ../debian/tmp/usr/bin/apport-retrace.py:69
msgid ""
"Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr ""
"Emplaçament de la còpia de la banca de donadas SQLite (per defaut : pas de "
"verificacion de la còpia)"

#: ../bin/apport-retrace.py:78 ../debian/tmp/usr/bin/apport-retrace.py:78
msgid "You cannot use -C without -S. Stopping."
msgstr "Podètz pas utilizar -C sens -S. Arrèst."

#. translators: don't translate y/n, apport currently only checks for "y"
#: ../bin/apport-retrace.py:111 ../debian/tmp/usr/bin/apport-retrace.py:111
msgid "OK to send these as attachments? [y/n]"
msgstr "D'acòrdi per mandar aquò coma pèças juntas ? [y/n]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:124
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:124
#: ../apport/ui.py:124
msgid "This package does not seem to be installed correctly"
msgstr "Sembla qu'aqueste paquet es pas installat corrèctament."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:129
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:129
#: ../apport/ui.py:129
#, python-format
msgid ""
"This is not an official %s package. Please remove any third party package "
"and try again."
msgstr ""
"Aqueste paquet es pas oficialament pres en carga per %s. Desinstallatz tot "
"paquet tèrç e tornatz ensajar."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:146
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:146
#: ../apport/ui.py:146
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""
"Las versions installadas d'unes paquets son obsolets. Metètz a jorn los "
"paquets seguents, puèi verificatz se lo problèma es encara present :%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:270
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:270
#: ../apport/ui.py:270
msgid "unknown program"
msgstr "programa desconegut"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:271
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:271
#: ../apport/ui.py:271
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr "O planhèm, lo programa « %s » a quitat d'un biais imprevist"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:273
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1312
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:273
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1312
#: ../apport/ui.py:273 ../apport/ui.py:1312
#, python-format
msgid "Problem in %s"
msgstr "Problèma dins %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:274
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:274
#: ../apport/ui.py:274
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""
"Vòstre ordenador possedís pas pro de memòria liura per analisar "
"automaticament lo problèma e mandar un rapòrt als desvolopaires."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:322
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:330
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:457
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:460
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:661
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1118
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1284
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1288
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:322
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:330
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:457
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:460
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:661
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1118
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1284
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1288
#: ../apport/ui.py:322 ../apport/ui.py:330 ../apport/ui.py:457
#: ../apport/ui.py:460 ../apport/ui.py:661 ../apport/ui.py:1118
#: ../apport/ui.py:1284 ../apport/ui.py:1288
msgid "Invalid problem report"
msgstr "Rapòrt d'incident invalid"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:323
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:323
#: ../apport/ui.py:323
msgid "You are not allowed to access this problem report."
msgstr "Sètz pas autorizat a accedir aqueste rapòrt d'incident."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:326
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:326
#: ../apport/ui.py:326
msgid "Error"
msgstr "Error"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:327
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:327
#: ../apport/ui.py:327
msgid "There is not enough disk space available to process this report."
msgstr "I a pas pro d'espaci de disc disponible per tractar aqueste rapòrt."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:411
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:411
#: ../apport/ui.py:411
msgid "No package specified"
msgstr "Cap de paquet pas especificat"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:412
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:412
#: ../apport/ui.py:412
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""
"Vos cal precisar un paquet o un PID. Utilizatz --help per mai d'informacions."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:435
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:435
#: ../apport/ui.py:435
msgid "Permission denied"
msgstr "Autorizacion refusada"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:436
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:436
#: ../apport/ui.py:436
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"Lo processus especificat vos aparten pas. Executar aqueste programa en tant "
"que proprietari del processus o en tant qu'administrator (root)."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:438
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:438
#: ../apport/ui.py:438
msgid "Invalid PID"
msgstr "PID invalida"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:439
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:439
#: ../apport/ui.py:439
msgid "The specified process ID does not belong to a program."
msgstr "L'ID de processus especificat aparten pas a cap de programa."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:458
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:458
#: ../apport/ui.py:458
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "L'escript  %s a pas pogut determinar un paquet afectat"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:461
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:461
#: ../apport/ui.py:461
#, python-format
msgid "Package %s does not exist"
msgstr "Lo paquet %s existís pas"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:485
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:673
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:678
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:485
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:673
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:678
#: ../apport/ui.py:485 ../apport/ui.py:673 ../apport/ui.py:678
msgid "Cannot create report"
msgstr "Impossible de crear lo rapòrt"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:500
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:563
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:500
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:546
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:563
#: ../apport/ui.py:500 ../apport/ui.py:546 ../apport/ui.py:563
msgid "Updating problem report"
msgstr "Mesa a jorn del rapòrt d'incident"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:501
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:501
#: ../apport/ui.py:501
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"Aqueste rapòrt es pas estat fach per vos o vos i sètz pas inscrich ; o es "
"tampat o s'agís d'un doblon.\n"
"Creatz un rapòrt novèl en utilizant « apport-bug »."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:510
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:510
#: ../apport/ui.py:510
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"Sètz pas lo redactor d'aqueste rapòrt d'incident. Es pus aisit de marcar un "
"bug coma duplicata que non pas de desplaçar vòstres comentaris e pèças "
"juntas sus un bug novèl.\n"
"Vos recomandam doncas de completar un senhalament de bug novèl en utilizant "
"\"apport-bug\"  e de ne far un comentari dins lo bug inicial.  \n"
"Sètz segur que volètz contunhar ?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:547
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:564
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:547
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:564
#: ../apport/ui.py:547 ../apport/ui.py:564
msgid "No additional information collected."
msgstr "Cap d'informacion suplementària es pas estada collectada."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:615
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:615
#: ../apport/ui.py:615
msgid "What kind of problem do you want to report?"
msgstr "Quin tipe de problèma volètz senhalar ?"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:632
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:632
#: ../apport/ui.py:632
msgid "Unknown symptom"
msgstr "Simptòma desconegut"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:633
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:633
#: ../apport/ui.py:633
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr "Lo simptòma « %s » es desconegut."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:664
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:664
#: ../apport/ui.py:664
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr ""
"Aprèp la tampadura d'aqueste messatge, clicatz sus la fenèstra de "
"l'aplicacion per la quala volètz senhalar un problèma."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:674
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:679
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:674
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:679
#: ../apport/ui.py:674 ../apport/ui.py:679
msgid "xprop failed to determine process ID of the window"
msgstr "xprop a pas pogut determinar l'ID del processus de la fenèstra"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:693
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:693
#: ../apport/ui.py:693
msgid "%prog <report number>"
msgstr "%prog <numèro del rapòrt>"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:695
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:695
#: ../apport/ui.py:695
msgid "Specify package name."
msgstr "Indicatz lo nom del paquet."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:697
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:748
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:697
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:748
#: ../apport/ui.py:697 ../apport/ui.py:748
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr ""
"Apondre un marcador suplementari pel rapòrt. Pòt èsser especificat mantun "
"còp."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:727
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:727
#: ../apport/ui.py:727
msgid ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""
"%prog [options] [symptom|pid|package|program path|.apport/.crash file]"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:730
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:730
#: ../apport/ui.py:730
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"Avia en mòde senhalament de bug. Necessita l'argument --package e --pid en "
"opcion, o simplament --pid. Se n'i a pas cap de provesit, aficha una lista "
"de simptòmas coneguts. (Implicit se un sol argument es provesit.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:732
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:732
#: ../apport/ui.py:732
msgid "Click a window as a target for filing a problem report."
msgstr "Clicatz sus la fenèstra per laquala volètz senhalar un problèma."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:734
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:734
#: ../apport/ui.py:734
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "Començar en mòde « mesa a jorn de bug ». Accèpta l'opcion --package"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:736
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:736
#: ../apport/ui.py:736
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr ""
"Efectua un senhalament de bug a prepaus d'un simptòma. (Implicit se lo nom "
"del simptòma es donat coma argument unic.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:738
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:738
#: ../apport/ui.py:738
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"Especifica un nom de paquet dins lo mode --file-bug. Aquò's opcional se --"
"pid es especificat. (Implicit se lo nom del paquet es donat coma argument "
"unic.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:740
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:740
#: ../apport/ui.py:740
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"Especificar un programa que s'executa en mòde « --file-bug ». S'aquò es "
"especificat, lo rapòrt de bug contendrà mai d'informacions. (implicita se "
"l’identificant del processus es passat coma argument unic)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:742
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:742
#: ../apport/ui.py:742
msgid "The provided pid is a hanging application."
msgstr "Lo pid provesit es una aplicacion que respond pas."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:744
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:744
#: ../apport/ui.py:744
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"Senhala lo bug a partir d'un fichièr .apport o .crash donat puslèu qu'a "
"partir de los que son en espèra dins %s. (Implicit se lo fichièr es donat "
"coma argument unic.)"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:746
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:746
#: ../apport/ui.py:746
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"En mòde de senhalament de bug, enregistra las informacions collectadas dins "
"un fichièr puslèu que de generar un rapòrt. Aqueste fichièr poirà èsser "
"utilizat pus tard a partir d'una autra maquina per mandar un rapòrt."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:750
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:750
#: ../apport/ui.py:750
msgid "Print the Apport version number."
msgstr "Aficha lo numèro de version d'Apport."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:889
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:889
#: ../apport/ui.py:889
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"Aquò va aviar apport-retrace dins una fenèstra de terminal per examinar lo "
"crash."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:890
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:890
#: ../apport/ui.py:890
msgid "Run gdb session"
msgstr "Aviar una sesilha gdb"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:891
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:891
#: ../apport/ui.py:891
msgid "Run gdb session without downloading debug symbols"
msgstr "Executar la sesilha gdb sens telecargar los simbòls de desbugatge"

#. TRANSLATORS: %s contains the crash report file name
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:893
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:893
#: ../apport/ui.py:893
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "Mesa a jorn de %s amb una traça de la pila totalament simbolica"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:969
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:979
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:969
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:979
#: ../apport/ui.py:969 ../apport/ui.py:979
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr ""
"Aqueste rapòrt d'incident s'aplica a un logicial qu'es pas pus installat per "
"aquesta distribucion."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:994
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:994
#: ../apport/ui.py:994
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr ""
"Lo problèma concernís lo programa %s qu'a cambiat dempuèi lo plantatge."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1041
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1075
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1290
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1041
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1075
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1290
#: ../apport/ui.py:1041 ../apport/ui.py:1075 ../apport/ui.py:1290
msgid "This problem report is damaged and cannot be processed."
msgstr "Aqueste rapòrt d'incident es damatjat e pòt pas èsser tractat."

#. package does not exist
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1045
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1045
#: ../apport/ui.py:1045
msgid "The report belongs to a package that is not installed."
msgstr "Lo rapòrt fa referéncia a un paquet pasinstallat."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1049
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1049
#: ../apport/ui.py:1049
msgid "An error occurred while attempting to process this problem report:"
msgstr ""
"Una error s'es producha al moment del tractament d'aqueste rapòrt "
"d'anomalia :"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1119
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1119
#: ../apport/ui.py:1119
msgid "Could not determine the package or source package name."
msgstr "Impossible de determinar lo nom del paquet o del paquet font."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1137
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1137
#: ../apport/ui.py:1137
msgid "Unable to start web browser"
msgstr "Impossible d'aviar lo navegador web"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1138
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1138
#: ../apport/ui.py:1138
#, python-format
msgid "Unable to start web browser to open %s."
msgstr "Impossible d'aviar lo navegador web per dobrir %s."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1238
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1238
#: ../apport/ui.py:1238
#, python-format
msgid "Please enter your account information for the %s bug tracking system"
msgstr ""
"Picatz las informacions de vòstre compte pel sistèma de seguit dels bugs %s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1250
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1250
#: ../apport/ui.py:1250
msgid "Network problem"
msgstr "Problèma de ret"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1252
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1252
#: ../apport/ui.py:1252
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"Impossible de se connectar a la banca de donadas dels plantatges. Verificatz "
"vòstra connexion a l'Internet."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1279
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1279
#: ../apport/ui.py:1279
msgid "Memory exhaustion"
msgstr "Memòria saturada"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1280
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1280
#: ../apport/ui.py:1280
msgid "Your system does not have enough memory to process this crash report."
msgstr ""
"Vòstre sistèma dispausa pas de pro de memòria per tractar aqueste rapòrt "
"d'incident."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1315
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1315
#: ../apport/ui.py:1315
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""
"Lo problèma pòt pas èsser senhalat :\n"
"\n"
"%s"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1371
#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1378
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1371
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1378
#: ../apport/ui.py:1371 ../apport/ui.py:1378
msgid "Problem already known"
msgstr "Problèma ja conegut"

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1372
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1372
#: ../apport/ui.py:1372
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"Aqueste problèma ja es estat senhalat dins lo rapòrt d'incident afichat per "
"vòstre navigador. Verificatz se podètz apondre d'informacions "
"complementàrias susceptiblas d'ajudar los desvolopaires."

#: ../debian/tmp/usr/lib/python2.7/dist-packages/apport/ui.py:1379
#: ../debian/tmp/usr/lib/python3/dist-packages/apport/ui.py:1379
#: ../apport/ui.py:1379
msgid "This problem was already reported to developers. Thank you!"
msgstr "Aqueste problèma es ja estat senhalat als desvolopaires. Mercé !"

#: ../data/apportcheckresume.py:67
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:67
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr ""
"Aquò s'es produsit precedentament al moment d'una mesa en velha e a empachat "
"lo sistèma de se reaviar corrèctament."

#: ../data/apportcheckresume.py:69
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:69
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr ""
"Aquò s'es produsit precedentament al moment d'una mesa en velha perlongada e "
"a empachat lo sistèma de se reaviar corrèctament."

#: ../data/apportcheckresume.py:74
#: ../debian/tmp/usr/share/apport/apportcheckresume.py:74
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"Lo processus de represa s'es blocat juste abans d'arribar a son tèrme e "
"apareisserà coma s'èra acabat normalament."

#: ../debian/tmp/usr/bin/apport-cli.py:74 ../bin/apport-cli.py:74
msgid "Press any key to continue..."
msgstr "Quichatz sus una tòca per contunhar..."

#: ../debian/tmp/usr/bin/apport-cli.py:81 ../bin/apport-cli.py:81
msgid "What would you like to do? Your options are:"
msgstr "Qué ne volètz far ? Las causidas son :"

#: ../debian/tmp/usr/bin/apport-cli.py:85 ../bin/apport-cli.py:85
#, python-format
msgid "Please choose (%s):"
msgstr "Fasètz una causida (%s) :"

#: ../debian/tmp/usr/bin/apport-cli.py:148 ../bin/apport-cli.py:148
#, python-format
msgid "(%i bytes)"
msgstr "(%i octets)"

#: ../debian/tmp/usr/bin/apport-cli.py:179 ../bin/apport-cli.py:179
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"Un còp que lo rapòrt d'incident serà estat mandat, completatz lo\n"
"formulari dobèrt automaticament dins vòstre navigador Web."

#: ../debian/tmp/usr/bin/apport-cli.py:182 ../bin/apport-cli.py:182
#, python-format
msgid "&Send report (%s)"
msgstr "&Mandar lo rapòrt (%s)"

#: ../debian/tmp/usr/bin/apport-cli.py:186 ../bin/apport-cli.py:186
msgid "&Examine locally"
msgstr "&Examinar en local"

#: ../debian/tmp/usr/bin/apport-cli.py:190 ../bin/apport-cli.py:190
msgid "&View report"
msgstr "&Veire lo rapòrt"

#: ../debian/tmp/usr/bin/apport-cli.py:191 ../bin/apport-cli.py:191
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr ""
"&Conservar lo fichièr del rapòrt per lo mandar ulteriorament o lo copiar "
"endacòm"

#: ../debian/tmp/usr/bin/apport-cli.py:192 ../bin/apport-cli.py:192
msgid "Cancel and &ignore future crashes of this program version"
msgstr ""
"Anullar e &ignorar los plantatges venents d'aquesta version del programa"

#: ../debian/tmp/usr/bin/apport-cli.py:194
#: ../debian/tmp/usr/bin/apport-cli.py:271
#: ../debian/tmp/usr/bin/apport-cli.py:303
#: ../debian/tmp/usr/bin/apport-cli.py:324 ../bin/apport-cli.py:194
#: ../bin/apport-cli.py:271 ../bin/apport-cli.py:303 ../bin/apport-cli.py:324
msgid "&Cancel"
msgstr "&Anullar"

#: ../debian/tmp/usr/bin/apport-cli.py:222 ../bin/apport-cli.py:222
msgid "Problem report file:"
msgstr "Fichièr del rapòrt d'incident :"

#: ../debian/tmp/usr/bin/apport-cli.py:228
#: ../debian/tmp/usr/bin/apport-cli.py:233 ../bin/apport-cli.py:228
#: ../bin/apport-cli.py:233
msgid "&Confirm"
msgstr "&Confirmar"

#: ../debian/tmp/usr/bin/apport-cli.py:232 ../bin/apport-cli.py:232
#, python-format
msgid "Error: %s"
msgstr "Error : %s"

#: ../debian/tmp/usr/bin/apport-cli.py:239 ../bin/apport-cli.py:239
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"Las informacions collectadas pòdon èsser mandadas als desvolopaires per \n"
"melhorar l'aplicacion. Aquò pòt prene qualques minutas."

#: ../debian/tmp/usr/bin/apport-cli.py:252 ../bin/apport-cli.py:252
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"Las informacions collectadas son mandadas al sistèma de seguit de bugs.\n"
"Aquò pòt prene qualques minutas."

#: ../debian/tmp/usr/bin/apport-cli.py:302 ../bin/apport-cli.py:302
msgid "&Done"
msgstr "&Acabat"

#: ../debian/tmp/usr/bin/apport-cli.py:308 ../bin/apport-cli.py:308
msgid "none"
msgstr "pas cap"

#: ../debian/tmp/usr/bin/apport-cli.py:309 ../bin/apport-cli.py:309
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "Seleccionat : % s. Causida multipla :"

#: ../debian/tmp/usr/bin/apport-cli.py:325 ../bin/apport-cli.py:325
msgid "Choices:"
msgstr "Causida multipla :"

#: ../debian/tmp/usr/bin/apport-cli.py:339 ../bin/apport-cli.py:339
msgid "Path to file (Enter to cancel):"
msgstr "Emplaçament del fichièr (tòca Entrada per anullar) :"

#: ../debian/tmp/usr/bin/apport-cli.py:345 ../bin/apport-cli.py:345
msgid "File does not exist."
msgstr "Lo fichièr existís pas."

#: ../debian/tmp/usr/bin/apport-cli.py:347 ../bin/apport-cli.py:347
msgid "This is a directory."
msgstr "Aquò's un repertòri."

#: ../debian/tmp/usr/bin/apport-cli.py:353 ../bin/apport-cli.py:353
msgid "To continue, you must visit the following URL:"
msgstr "Per contunhar, vos cal anar a aquela adreça :"

#: ../debian/tmp/usr/bin/apport-cli.py:355 ../bin/apport-cli.py:355
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"Podètz dobrir un navigador Web ara, o picar aquesta URL dins un navigador "
"sus un autre ordenador."

#: ../debian/tmp/usr/bin/apport-cli.py:357 ../bin/apport-cli.py:357
msgid "Launch a browser now"
msgstr "Aviar un navigador Web ara"

#: ../debian/tmp/usr/bin/apport-cli.py:371 ../bin/apport-cli.py:371
msgid "No pending crash reports. Try --help for more information."
msgstr ""
"Pascap de rapòrt d'incident en espèra. Ensajatz --help per mai "
"d'informacions."

#~ msgid "&Details..."
#~ msgstr "&Detalhs"

#~ msgid "Restart _Program"
#~ msgstr "Tornar aviar lo _programa"

#~ msgid "Content of the report"
#~ msgstr "Contengut del rapòrt"

#~ msgid "&Report Problem..."
#~ msgstr "&Senhalar lo problèma..."

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other\n"
#~ "private information), you can help to improve the application by reporting\n"
#~ "the problem."
#~ msgstr ""
#~ "Se fasiatz pas res de confidencial (picada de senhals o d'autras\n"
#~ "informacions privadas), podètz ajudar a melhorar l'aplicacion en senhalant\n"
#~ "lo problèma."

#, python-format
#~ msgid "%s closed unexpectedly on %s at %s."
#~ msgstr "%s a quitat d'un biais imprevist lo %s à %s"

#~ msgid "Your system encountered a serious kernel problem."
#~ msgstr "Un problèma seriós amb lo nucli s'es produch sus vòstre sistèma."

#, python-format
#~ msgid "&Send complete report (recommended; %s)"
#~ msgstr "&Mandar un rapòrt complet (recomandat ; %s)"

#~ msgid ""
#~ "You can help the developers to fix the package by reporting the problem."
#~ msgstr ""
#~ "Podètz ajudar los desvolopaires a resòlvre lo problèma en lo senhalant."

#~ msgid "You can help the developers to fix the problem by reporting it."
#~ msgstr ""
#~ "Podètz ajudar los desvolopaires a corregir aqueste problèma en lo senhalant."

#, python-format
#~ msgid "Send &reduced report (slow Internet connection; %s)"
#~ msgstr "Mandar un rap*rt ab&reujat (connexion Internet lenta ; %s)"

#, python-format
#~ msgid "The package \"%s\" failed to install or upgrade."
#~ msgstr "L'installacion o la mesa a jorn dl paquet « %s » a fracassat."

#~ msgid ""
#~ "This occured during a previous suspend and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Aquò s'es produch al moment d'una mesa en velha precedenta ;  aquò l'empacha "
#~ "de tornar prene corrèctament."

#~ msgid ""
#~ "This occured during a previous hibernate and prevented it from resuming "
#~ "properly."
#~ msgstr ""
#~ "Aquò s'es produch al moment d'una ivernacion precedenta ; aquò l'empacha de "
#~ "tornar prene corrèctament."

#, no-c-format, python-format
#~ msgid "Complete report (recommended; %s)"
#~ msgstr "Rapòrt complet (recomandat ; %s)"

#~ msgid "Application problem"
#~ msgstr "Problèma logicial"

#, no-c-format
#~ msgid ""
#~ "<span weight=\"bold\" size=\"larger\">Sorry, the package \"%s\" failed to "
#~ "install or upgrade.</span>"
#~ msgstr ""
#~ "<span weight=\"bold\" size=\"larger\">O planhèm, fracàs al moment de "
#~ "l'installacion o de la mesa a jorn del paquet « %s ».</span>"

#~ msgid ""
#~ "<big><b>Send problem report to the developers?</b></big>\n"
#~ "\n"
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "<big><b>Mandar un rapòrt d'incident als desvolopaires ?</b></big>\n"
#~ "\n"
#~ "Un còp lo rapòrt mandat, emplenatz lo formulari afichat automaticament per "
#~ "vòstre navigador Web."

#, no-c-format, python-format
#~ msgid "Reduced report (slow Internet connection; %s)"
#~ msgstr "Rapòrt abreujat (connexion Internet lenta ; %s)"

#~ msgid ""
#~ "This will remove some large items from the report. These are very useful for "
#~ "developers to debug the problem, but might be too big for you to upload if "
#~ "you have a slow internet connection."
#~ msgstr ""
#~ "De partidas voluminosas van èsser suprimidas del rapòrt. Son fòrça utilas "
#~ "als desvolopaires per resòlvre lo problèma, mas se pòdon revelar tròp "
#~ "pesugas al moment de lor transmission se dispausatz pas que d'una connexion "
#~ "Internet de bas debit."

#~ msgid "_Ignore future crashes of this program version"
#~ msgstr "_Ignorar los plantatges venents d'aquesta version del programa"

#~ msgid "_Report Problem..."
#~ msgstr "Senhalar aqueste p_roblèma..."

#~ msgid "Package problem"
#~ msgstr "Problèma de paquet"

#~ msgid "Kernel problem"
#~ msgstr "Problèma de nucli"

#~ msgid ""
#~ "If you were not doing anything confidential (entering passwords or other "
#~ "private information), you can help to improve the application by reporting "
#~ "the problem."
#~ msgstr ""
#~ "Se fasiatz pas res de confidencial (picada de senhals o d'informacions "
#~ "privadas), podètz ajudar a melhorar l'aplicacion en senhalant lo problèma."

#~ msgid "_Send Report"
#~ msgstr "_Mandar lo rapòrt"

#~ msgid "%prog [options] <apport problem report | crash ID>"
#~ msgstr "%prog [options] <apport problem report | crash ID>"

#~ msgid "incorrect number of arguments; use --help for a short help"
#~ msgstr ""
#~ "Nombre d'arguments incorrècte ; utilizatz --help per una ajuda succincta"

#~ msgid ""
#~ "you either need to do a local operation (-s, -g, -o) or supply an "
#~ "authentication file (--auth); see --help for a short help"
#~ msgstr ""
#~ "Vos cal far una operacion locala (-s, -g, -o) o provesir un fichièr "
#~ "d'autentificacion (--auth) ; vejatz --help per una ajuda succinta"

#, python-format
#~ msgid "This is not a genuine %s package"
#~ msgstr "Aquò's pas es pas un paquet %s autentic"

#~ msgid "Send this data to the developers?"
#~ msgstr "Mandar aquelas donadas als desvolopaires ?"

#, python-format
#~ msgid "Sorry, the package \"%s\" failed to install or upgrade."
#~ msgstr ""
#~ "O planhèm, lo paquet « %s » a pas pogut èsser installat o mes a jorn."

#, python-format
#~ msgid "Sorry, %s closed unexpectedly"
#~ msgstr "O planhèm, %s a quitat d'un biais imprevist"

#~ msgid ""
#~ "After the problem report has been sent, please fill out the form in the "
#~ "automatically opened web browser."
#~ msgstr ""
#~ "Aprèp lo mandadís del rapòrt d'incident, completatz lo formulari dobèrt "
#~ "automaticament dins lo navigador Web."

#~ msgid "Generic error"
#~ msgstr "Error generica"

#~ msgid "&Ignore future crashes of this program version"
#~ msgstr "&Ignorar los plantatges que venon d'aquesta version del logicial"

#, python-format
#~ msgid "Sorry, the program \"%s\" closed unexpectedly."
#~ msgstr "O planhèm, lo programa « %s » a quitat d'un biais imprevist."

#~ msgid "Restart &Program"
#~ msgstr "Reaviar lo &programa"

#, python-format
#~ msgid "Sorry, %s closed unexpectedly."
#~ msgstr "O planhèm, %s a quitat d'un biais imprevist."

#~ msgid "&Send"
#~ msgstr "&Mandar"

#, python-format
#~ msgid "Sorry, the application %s has closed unexpectedly."
#~ msgstr "O planhèm, l'aplicacion %s a quitat d'un biais imprevist."

#~ msgid "Your system might become unstablenow and might need to be restarted."
#~ msgstr "Vòstre sistèma poiriá venir instable e necessitar una reaviada."
